Simple migration
Azure-Samples/active-directory-dotnet-v1-to-v2 pull request #32
Opened 2021-04-06 14:53 UTC by bgavrilMS

Current sample is very complex, as it was used for testing. 

New sample is a console app that shows a very simple transition from ADAL v5 to MSAL. 

![image](https://user-images.githubusercontent.com/12273384/113730843-2579f880-96f0-11eb-9ef1-190c5edfc1ea.png)

I propose we keep the old sample as a branch only.

2021-04-06 14:54 UTC, bgavrilMS commented on TokenCacheMigration/ADAL2MSAL/AdalFileCache.cs
> +    class AdalFileCache : TokenCache
I think this is the most important simplification: 

- ADAL no longer uses MSAL cache format

2021-04-27 08:19 UTC, jmprieur requested changes
When trying to build this branch, I get the following error:

```Shell
C:\ghs\s\active-directory-dotnet-v1-to-v2\TokenCacheMigration\ADAL2MSAL\Program.cs(103,60): error CS7036: There is no argument given that corresponds to the required formal parameter 'msalCacheFilePath' of 'AdalFileCache.AdalFileCache(string, string)' [C:\ghs\s\active-
directory-dotnet-v1-to-v2\TokenCacheMigration\ADAL2MSAL\ADAL2MSAL.csproj]
```

2021-04-27 08:19 UTC, jmprieur commented on TokenCacheMigration/ADAL2MSAL/AdalFileCache.cs
> +﻿using Microsoft.IdentityModel.Clients.ActiveDirectory;
@bgavrilMS : did you move this file?

2021-12-09 18:34 UTC, bgavrilMS commented on TokenCacheMigration/ADAL2MSAL/AdalFileCache.cs
> +﻿using Microsoft.IdentityModel.Clients.ActiveDirectory;
Fixed.

2022-01-05 23:04 UTC, merged